String scriptBD2() {
  return "create table carrito"
      "("
      "	id INTEGER PRIMARY KEY,"
      "	descripcion varchar(150) not null"
      ");"
      "create table supermercado"
      "("
      "	id INTEGER PRIMARY KEY,"
      "	nombre varchar(150) not null,"
      "	longitud float not null,"
      "	latitud float not null,"
      "	descripcion varchar(150) not null"
      ");"
      "create table categoria"
      "("
      "	id INTEGER PRIMARY KEY,"
      "	nombre varchar(150) not null,"
      "	descripcion varchar(150) not null,"
      "	imagen varchar(150) not null"
      ");"
      "create table cliente"
      "("
      "	id INTEGER PRIMARY KEY,"
      "	ci int not null,"
      "	nombre varchar(150) not null,"
      "	telf int not null,"
      "	direccion varchar(150) not null,"
      " idcarrito int not null,"
      " FOREIGN KEY (idcarrito) REFERENCES carrito (id) "
      "  	ON UPDATE CASCADE "
      "  	ON DELETE CASCADE"
      ");"
      "create table tipopago"
      "("
      "	id INTEGER PRIMARY KEY,"
      "	tipo_envio varchar(150) not null,"
      "	forma_pago varchar(150) not null,"
      "	descripcion varchar(150) not null,"
      "    idcarrito int not null,"
      "    FOREIGN KEY (idcarrito) REFERENCES carrito (id) "
      "  	ON UPDATE CASCADE "
      "  	ON DELETE CASCADE"
      ");"
      "create table factura"
      "("
      "	id INTEGER PRIMARY KEY,"
      "	fecha Timestamp not null,"
      "	montoT decimal(4,2) not null,"
      "	idtipopago int not null,"
      "	FOREIGN KEY (idtipopago) REFERENCES tipopago (id) "
      "  	ON UPDATE CASCADE "
      "  	ON DELETE CASCADE"
      ");"
      "create table sucursal"
      "("
      "	id INTEGER PRIMARY KEY,"
      "	nombre varchar(150) not null,"
      "	descripcion varchar(150) not null,"
      "	longitud float not null,"
      "	latitud float not null,"
      "	idsupermercado int not null,"
      "	FOREIGN KEY (idsupermercado) REFERENCES supermercado (id) "
      "  	ON UPDATE CASCADE "
      "  	ON DELETE CASCADE"
      ");"
      "create table producto"
      "("
      "	id INTEGER PRIMARY KEY,"
      "	nombre varchar(150) not null,"
      "	precio decimal(4,2) not null,"
      "	descripcion varchar(150) not null,"
      "	imagen varchar(150) not null,"
      "	idcategoria int not null,"
      "	FOREIGN KEY (idcategoria) REFERENCES categoria (id) "
      "  	ON UPDATE CASCADE "
      "  	ON DELETE CASCADE"
      ");"

      "create table producto_carrito"
      "("
      "	id INTEGER PRIMARY KEY,"
      " idCliente int not null,"
      "	nombre varchar(150) not null,"
      "	precio decimal(4,2) not null,"
      "	descripcion varchar(150) not null,"
      "	imagen varchar(150) not null,"
      "	idcategoria int not null,"
      "	FOREIGN KEY (idcategoria) REFERENCES categoria (id) "
      "  	ON UPDATE CASCADE "
      "  	ON DELETE CASCADE"
      ");"

      "create table detalle_prod_carrito"
      "("
      "	id INTEGER PRIMARY KEY,"
      "    cantidad int not null,"
      "    descripcion varchar(150) not null,"
      "	idproducto int not null,"
      "	idcarrito int not null,"
      "	FOREIGN KEY (idproducto) REFERENCES producto (id) "
      "  	ON UPDATE CASCADE "
      "  	ON DELETE CASCADE,"
      "    FOREIGN KEY (idcarrito) REFERENCES carrito (id) "
      "  	ON UPDATE CASCADE "
      "  	ON DELETE CASCADE"
      ");"
      "create table detalle_prod_sucursal"
      "("
      "	id INTEGER PRIMARY KEY,"
      "	idproducto int not null,"
      "	idsucursal int not null,"
      "	FOREIGN KEY (idproducto) REFERENCES producto (id) "
      "  	ON UPDATE CASCADE "
      "  	ON DELETE CASCADE,"
      "	FOREIGN KEY (idsucursal) REFERENCES sucursal (id) "
      "  	ON UPDATE CASCADE "
      "  	ON DELETE CASCADE"
      ");"
      "insert into carrito(descripcion)values"
      "('Si desea puede agregar mas productos'),"
      "('Si desea puede agregar mas productos'),"
      "('Si desea puede agregar mas productos'),"
      "('Si desea puede agregar mas productos'),"
      "('Si desea puede agregar mas productos');"
      "insert into supermercado(nombre,longitud,latitud,descripcion)values"
      "('Fidalga',-17.800487,-63.183309,'Dirección: Avenida El Trompillo 632, Santa Cruz de la Sierra'),"
      "('Hipermaxi',-17.784906,-63.211839,'Direccion: Avenida Roca y Coronado #800'),"
      "('IC Norte',-17.772701, -63.203551,'Direccion: Avenida Busch, 3cer anillo interno'),"
      "('Supermercado Tia',-17.778826,-63.181744,'Direccion: Centro, Santa Cruz de la Sierra');"
      "insert into categoria(nombre,descripcion,imagen	)values"
      "('Carnes y Embutidos','Usted dispondrá de la mejor selección de carnes de nuestras razas autóctonas.','carne-y-embutidos5.jpg'),"
      "('Frutas y Verduras',' Una cuidada y selecta variedad de frutas y verduras directamente del agricultor a tu mesa.','frutas-y-verduras-ecologicas6.jpg'),"
      "('Panadería y Dulces','Para todos los gustos: de trigo, centeno, integral, cereales, panecillos, chocolate con chili, con fresas.','panaderia-y-dulces4.jpg'),"
      "('Huevos, Lácteos y Cafe','Huevos ricos en antioxidantes, los mejores productos lácteos y sus derivados: queso, yogur.','huevos-lacteos-y-cafe4.jpg'),"
      "('Aceite, Pastas','Aceites de altísima calidad, en aroma y sabor.','aceite-pasta-y-legumbres4.jpg'),"
      "('Conservas y Comida Preparada','Descubra la gran variedad, calidad y facilidad de los preparados ecológicos.','conservas-y-comidas-preparadas4.jpg'),"
      "('Zumos y Bebidas',' Zumos que aportan un mayor número de vitaminas naturales.','zumos-y-bebidas4.jpg'),"
      "('Aperitivos','Con el mejor aceite de oliva se elaboran estos productos de la mayor calidad del mercado.','aperitivos4.jpg'),"
      "('Infantil','Todo 100% natural. Desde pañales de tela a la alimentación más cuidada y especial para tu bebé.','infantil4.jpg'),"
      "('Cosmética y Cuidado Personal','La auténtica cosmética natural, basada en el aceite de oliva virgen ecológico.','cosmetica-y-cuidado-personal4.jpg'),"
      "('Hogar y Limpieza','Limpieza ecológica de verdad.','hogar-y-limpieza4.jpg');"
      "insert into cliente(ci,nombre,telf,direccion,idcarrito)values"
      "(111,'Wilar ADS',60826862,'Av. Trompillo',1),"
      "(222,'Noelia Lazarte',60826862,'Av. Brasil',2),"
      "(333,'Sergio Ramos',60826862,'Av. Beni',3),"
      "(444,'Paola Santos',60826862,'Av. Banzer',4),"
      "(555,'Camila Diaz',60826862,'Av. Pirai',5),"
      "(666,'Franco Antonio Penarrieta',5321862,'Radial 13',6);"
      "insert into tipopago(tipo_envio,forma_pago,descripcion,idcarrito) values"
      "('costo de envio 15 bs ','pago con efectivo','mostrar Carnet',1),"
      "('costo de envio 15 bs','pago con tarjeta','mostrar Carnet',2),"
      "('costo de envio 15 bs','deposito en numero d cuenta','mostrar Carnet',3),"
      "('regocer personalmente ','pago con efectivo','mostrar Carnet',4),"
      "('regocer personalmente ','pago con tarjeta','mostrar Carnet',5),"
      "('regocer personalmente ','deposito en numero d cuenta','mostrar Carnet',1);"
      "insert into factura(fecha,montot,idtipopago)values"
      "('2020-05-01 11:00:00',35,1),"
      "('2020-06-10 15:00:00',35,2),"
      "('2020-07-15 13:00:00',35,3),"
      "('2020-05-11 09:00:00',35,4),"
      "('2020-06-19 20:00:00',35,5),"
      "('2020-07-21 21:00:00',35,6);"
      "insert into sucursal(nombre,descripcion,longitud,latitud,idsupermercado)values"
      "('Fidalga','Dirección: Avenida El Trompillo 632, Santa Cruz de la Sierra' ,-17.800487,-63.183309,1),"
      "('Fidalga Equipetrol','Dr Fermín Peralta, Santa Cruz de la Sierra',-17.760578, -63.198295,1),"
      "('Fidalga Reyes','Avenida 26 De Febrero, Santa Cruz de la Sierra',-17.789684, -63.194297,1),"
      "('Super Sur Fidalga SRL Central','Av. Rene Moreno # 212 esquina, Diego de Mendoza, Santa Cruz de la Sierra',-17.793779, -63.180003,1),"
      "('Super Sur Fidalga SRL Central','Av. Rene Moreno # 212 esquina, Diego de Mendoza, Santa Cruz de la Sierra',-17.793793, -63.179995,1),"
      "('Fidalga Hamacas','Av. Beni # 500 esquina, Santa Cruz de la Sierra',-17.755143, -63.171688,1),"
      "('Hipermaxi','Direccion: Avenida Roca y Coronado #800',-17.784906,-63.211839,2),"
      "('Hipermaxi Norte','Av Noel Kempff Mercado, Santa Cruz de la Sierra',-17.760227, -63.177996,2),"
      "('Hipermaxi4to','Avenida Cuarto Anillo, Santa Cruz de la Sierra',-17.749738, -63.185346,2),"
      "('Hipermaxi Cañoto','Avenida Cañoto, Santa Cruz de la Sierra',-17.778861, -63.188279,2),"
      "('Hipermaxi Florida','Florida, Santa Cruz de la Sierra',-17.781967, -63.183608,2),"
      "('Hipermaxi Las Palmas','Doble vía La Guardia, Santa Cruz de la Sierra',-17.810653, -63.208472,2),"
      "('IC Norte','Direccion: Avenida Busch, 3cer anillo interno',-17.772701, -63.203551,3),"
      "('Supermercado Tia','Direccion: Centro, Santa Cruz de la Sierra',-17.778826,-63.181744,4),"
      "('Tía','Cuarto Anillo, Santa Cruz de la Sierra',-17.755194, -63.199832,4),"
      "('Supermercados Tia','Av Alemania, Santa Cruz de la Sierra',-17.754689, -63.165413,4);"
      "insert into producto(nombre,precio,descripcion,imagen,idcategoria)values"
      "('Jamon Sandwichero Carne SOFIA',35,'1 Kg. Jamon Sandwichero Carne SOFIA','Jamon.jpg',1),"
      "('Hamburguesa de Res SOFIA',5.30,'Hamburguesa de Res Express de 2 unidades','Jamon.jpg',1),"
      "('Pollo SOFIA',15.20,'1 Kg. Pollo SOFIA','pollo.jpg',1),"
      "('Salchicha SOFIA',20.10,'Salchicha de Carne SOFIA','salchicha.jpg',1),"
      "('Carne de Res',34,'1 Kg. Carne de Res','carne.jpg',1),"
      "('Manzana',10.20,'1 Kg. Manzana Roja','manzana.jpg',2),"
      "('Tomate',9.50,'1 Kg. Tomate','tomate.jpg',2),"
      "('Cebolla',12.30,'1 Kg. Cebolla','cebolla.jpg',2),"
      "('Banana',7.60,'1 Kg. Banana','banana.jpg',2),"
      "('Pera',9.50,'1 Kg. Pera','pera.jpg',2),"
      "('Pan frances',1,'1 Bs la unidad de Pan Frances ','panfrances.jpg',3),"
      "('panintegral',11.30,'Pan Molde integral','panintegral.jpg',3),"
      "('Rollitos de Canela',3.20,'Rollitos de Canela la unidad','rollitodecanela.jpg',3),"
      "('Donuts',6.40,'Donuts Tortita','donuts.jpg',3),"
      "('Pie de Limon',35,'Pie de Limon','pailimon.jpg',3),"
      "('Huevos',27,'25 Huevos','huevo.jpg',4),"
      "('Leche deslactosada PIL',8.50,'1 Ltr Leche deslactosada PIL','leche.jpg',4),"
      "('Queso',17,'1 Kg. Queso','queso.jpg',4),"
      "('Nescafe Original 200 gr.',39,' Nescafe Original','cafe.jpg',4),"
      "('Toddy',14,'Frasco de 400 gr de puro Toddy Original','toddy.jpg',4),"
      "('Aceite de Oliva',34,'Aceite de Oliva Extra Virgen 250 cc','aceitedeoliva.jpg',5),"
      "('Aceite Fino Vegetal',11.88,'Aceite Fino Vegetal Gisarol 900 ml','aceitefino.jpg',5),"
      "('Fideos Lazzaroni',4.50,'Fideos Lazzaroni','fideo.jpg',5),"
      "('Fideo Don Victorio Surtido 400 gr',8.40,'La mejor selección de trigo, especialmente combinados y madurados en su punto','fideodonvictorio.jpg',5);"
      "insert into detalle_prod_carrito(cantidad,descripcion,idproducto,idcarrito) values"
      "(5,'desea ampliar su compra?',1,1),"
      "(1,'desea ampliar su compra?',2,1),"
      "(3,'desea ampliar su compra?',3,1),"
      "(2,'desea ampliar su compra?',4,1),"
      "(9,'desea ampliar su compra?',5,1),"
      "(7,'desea ampliar su compra?',6,1),"
      "(4,'desea ampliar su compra?',7,1),"
      "(1,'desea ampliar su compra?',8,1),"
      "(4,'desea ampliar su compra?',9,1),"
      "(1,'desea ampliar su compra?',10,1),"
      "(5,'desea ampliar su compra?',11,1),"
      "(5,'desea ampliar su compra?',12,1),"
      "(5,'desea ampliar su compra?',10,2),"
      "(8,'desea ampliar su compra?',13,2),"
      "(7,'desea ampliar su compra?',11,2),"
      "(4,'desea ampliar su compra?',19,3),"
      "(5,'desea ampliar su compra?',15,3),"
      "(2,'desea ampliar su compra?',23,4),"
      "(6,'desea ampliar su compra?',21,4),"
      "(5,'desea ampliar su compra?',11,4),"
      "(5,'desea ampliar su compra?',15,4),"
      "(5,'desea ampliar su compra?',11,5),"
      "(1,'desea ampliar su compra?',12,5),"
      "(3,'desea ampliar su compra?',13,5),"
      "(5,'desea ampliar su compra?',14,5),"
      "(6,'desea ampliar su compra?',15,5),"
      "(2,'desea ampliar su compra?',21,5);"
      "insert into detalle_prod_sucursal(idproducto,idsucursal)values"
      "(1,1),"
      "(2,1),"
      "(3,1),"
      "(4,1),"
      "(5,1),"
      "(6,1),"
      "(7,1),"
      "(8,1),"
      "(9,1),"
      "(10,1),"
      "(11,1),"
      "(1,2),"
      "(2,2),"
      "(3,2),"
      "(4,2),"
      "(5,2),"
      "(6,2),"
      "(1,3),"
      "(2,3),"
      "(7,3),"
      "(8,3),"
      "(9,3),"
      "(10,3),"
      "(11,3),"
      "(16,4),"
      "(15,4),"
      "(17,4),"
      "(18,4),"
      "(19,4),"
      "(20,4),"
      "(21,4),"
      "(22,4),"
      "(23,4),"
      "(24,4),"
      "(4,5),"
      "(5,5),"
      "(6,5),"
      "(7,5),"
      "(8,5),"
      "(9,5),"
      "(10,5),"
      "(11,5),"
      "(1,6),"
      "(2,6),"
      "(3,6),"
      "(4,6),"
      "(1,7),"
      "(2,7),"
      "(7,7),"
      "(8,7),"
      "(9,7),"
      "(11,7),"
      "(16,8),"
      "(15,8),"
      "(17,8),"
      "(18,9),"
      "(19,9),"
      "(20,9),"
      "(21,9),"
      "(22,9),"
      "(23,9),"
      "(24,9),"
      "(1,10),"
      "(2,10),"
      "(3,10),"
      "(4,10),"
      "(5,10),"
      "(6,10),"
      "(7,11),"
      "(8,11),"
      "(9,11),"
      "(10,11),"
      "(11,11),"
      "(1,12),"
      "(2,12),"
      "(4,12),"
      "(5,12),"
      "(6,12),"
      "(1,13),"
      "(2,13),"
      "(7,13),"
      "(8,13),"
      "(9,13),"
      "(10,13),"
      "(11,14),"
      "(16,14),"
      "(15,14),"
      "(17,14),"
      "(18,15),"
      "(19,15),"
      "(20,16),"
      "(21,16),"
      "(22,16),"
      "(23,16),"
      "(24,16);";
}

/*
      "create table usuario"
      "("
      "	id INTEGER PRIMARY KEY,"
      "	usuario varchar(150) not null"
      " password varchar(150 not null)"
      " idcliente int not null"
      " FOREIGN KEY (idcliente) REFERENCES cliente (id) "
      ");"
*/

/*
     " insert into usuario(usuario,password,idcliente) values"
      " ('111','111',1),"
      " ('fff','123',6),"
      "('222','222',1),"
      "('333','333',3);"
*/
